In [2]:
import torch
print(torch.__version__)

2.9.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is Available")
    print(f"The GPU is : {torch.cuda.get_device_name(0)}")
else:
    print("No GPU Available")

GPU is Available
The GPU is : NVIDIA GeForce RTX 3060


In [4]:
a = torch.empty(2, 3)
a

tensor([[9.9655e-12, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [5]:
m1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
m2 = torch.tensor([[5, 6, 7], [10 ,11, 12]])


Basic Math Operations

In [6]:
# m1 + m2
# m1 - m2
# m1 * m2
# m1 / m2
# m2 // m1

3D Tensor

In [7]:
array3D = torch.randint(size = (3, 3, 2), low = 0, high = 10)
array3D

tensor([[[6, 4],
         [3, 8],
         [0, 4]],

        [[5, 2],
         [5, 7],
         [8, 6]],

        [[5, 0],
         [5, 1],
         [7, 8]]])

Rounding values

In [8]:
a = torch.tensor([[0.555, 1.333, 2.777], [1.22, 2.533, 3.666]])
a

tensor([[0.5550, 1.3330, 2.7770],
        [1.2200, 2.5330, 3.6660]])

In [9]:
# torch.round(a)
# torch.ceil(a)
# torch.floor(a)

In [10]:
a.shape

torch.Size([2, 3])

Reduction Operations

In [11]:
a = torch.tensor([[2, 3, 4], [3, 6, 7]], dtype = torch.float64)

In [12]:
a.sum()
a.sum(axis=0)
a.sum(axis=1)

tensor([ 9., 16.], dtype=torch.float64)

In [13]:
a.mean()
a.mean(axis=0)
a.mean(axis=1)

tensor([3.0000, 5.3333], dtype=torch.float64)

In [14]:
a.median()
a.median(axis = 1)


torch.return_types.median(
values=tensor([3., 6.], dtype=torch.float64),
indices=tensor([1, 1]))

In [15]:
a.std()
a.std(axis=1)

tensor([1.0000, 2.0817], dtype=torch.float64)

Matrix Operations

In [16]:
m1 = torch.tensor([[1, 2, 3], [4, 5, 10]])

In [17]:
torch.transpose(m1, 0, 1)

tensor([[ 1,  4],
        [ 2,  5],
        [ 3, 10]])

In [18]:
m2 = torch.tensor([[1, 2, 10], [4, 11, 6], [7, 8, 9]], dtype=torch.float64)
m2.inverse()

tensor([[-0.1318, -0.1602,  0.2532],
        [-0.0155,  0.1576, -0.0879],
        [ 0.1163, -0.0155, -0.0078]], dtype=torch.float64)

In [19]:
torch.det(m2)

tensor(-387., dtype=torch.float64)

In [20]:
m1 = torch.randint(size = (3, 3), low = 1, high = 4)
m2 = torch.randint(size = (3, 3), low = 1, high = 4)

print(m1)
print(m2)

tensor([[2, 1, 2],
        [1, 1, 3],
        [2, 3, 2]])
tensor([[1, 3, 2],
        [1, 1, 1],
        [1, 2, 1]])


In [21]:
m3 = torch.matmul(m1, m2)
m3

tensor([[ 5, 11,  7],
        [ 5, 10,  6],
        [ 7, 13,  9]])

Special Functions

In [22]:
m1 = torch.tensor([[1, 2, 3], [3, 4, 4]])

In [23]:
m1.log()

tensor([[0.0000, 0.6931, 1.0986],
        [1.0986, 1.3863, 1.3863]])

In [24]:
m1.sqrt()

tensor([[1.0000, 1.4142, 1.7321],
        [1.7321, 2.0000, 2.0000]])

In [25]:
m1.sigmoid()

tensor([[0.7311, 0.8808, 0.9526],
        [0.9526, 0.9820, 0.9820]])

In [26]:
m1.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [ 0.1411, -0.7568, -0.7568]])

CPU vs GPU Comparison

In [27]:
import time
device = torch.device("cuda")

In [28]:
# Matrices in CPU

matrix1 = torch.randn(10000, 10000)
matrix2 = torch.randn(10000, 10000)

print(matrix1)
print(matrix2)

# Multiplication in CPU and Record the time
start_time = time.time()
mul = torch.matmul(matrix1, matrix2)
end_time = time.time()

cpu_time = end_time - start_time

print(f"Time taken by CPU: {cpu_time} seconds")

# Move the matrices to GPU
matrix1 = matrix1.to(device)
matrix2 = matrix2.to(device)

start_time = time.time()
mul = torch.matmul(matrix1, matrix2)
end_time = time.time()

gpu_time = end_time - start_time

print(f"Time taken by GPU: {gpu_time} seconds")

print(cpu_time/gpu_time)


tensor([[-0.7339,  0.4783, -0.4515,  ...,  0.3778,  0.3053,  1.4982],
        [ 0.1609, -0.6555, -1.0502,  ...,  1.6699, -0.7340, -0.3498],
        [ 1.9293, -0.3299, -1.1226,  ..., -0.1374, -0.1645,  1.7278],
        ...,
        [ 0.5316,  0.0268, -0.4019,  ...,  0.0229,  1.0827,  0.9040],
        [-0.9134, -0.9434,  0.7796,  ...,  0.2558, -0.0430, -0.0813],
        [-1.3644,  0.3940,  1.0025,  ...,  0.6914, -1.0670,  2.1756]])
tensor([[-1.0331,  0.2183, -0.8521,  ...,  0.9339,  0.5599,  0.6353],
        [ 1.2573, -0.0036,  0.0356,  ...,  1.4781,  0.2730,  0.4765],
        [-1.0005, -0.1599,  0.3516,  ..., -1.5757, -1.1888,  1.0283],
        ...,
        [-0.2776,  0.1982, -0.4831,  ...,  0.2233,  0.2048, -1.7261],
        [ 0.1169, -0.0938, -0.6530,  ..., -1.7883,  1.1721, -0.8086],
        [ 1.0485, -0.7582,  0.7076,  ..., -0.5694,  0.9689, -0.4909]])
Time taken by CPU: 2.6285901069641113 seconds
Time taken by GPU: 0.06512713432312012 seconds
40.36090539348301
